set_property SRC_FILE_INFO {cfile:d:/GitHub/Filtro-FPGA/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0.xdc rfile:../../../filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0.xdc id:1 order:EARLY scoped_inst:ethernet_core_0_A/inst/xmac/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/GitHub/Filtro-FPGA/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0.xdc rfile:../../../filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0.xdc id:2 order:EARLY scoped_inst:ethernet_core_0_B/inst/xmac/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/GitHub/Filtro-FPGA/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0.xdc rfile:../../../filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0.xdc id:3 order:EARLY scoped_inst:ethernet_core_0_A/inst/xpcs/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/GitHub/Filtro-FPGA/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0.xdc rfile:../../../filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0.xdc id:4 order:EARLY scoped_inst:ethernet_core_0_B/inst/xpcs/inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/GitHub/Filtro-FPGA/filter_10g_sfp.srcs/constrs_1/new/udp_ip_10g.xdc rfile:../../../filter_10g_sfp.srcs/constrs_1/new/udp_ip_10g.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:d:/GitHub/Filtro-FPGA/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0_clocks.xdc rfile:../../../filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0_clocks.xdc id:6 order:LATE scoped_inst:ethernet_core_0_A/inst/xmac/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/GitHub/Filtro-FPGA/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0_clocks.xdc rfile:../../../filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0_clocks.xdc id:7 order:LATE scoped_inst:ethernet_core_0_B/inst/xmac/inst} [current_design]
current_instance ethernet_core_0_A/inst/xmac/inst
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells bd_efdb_xmac_0_core/rx/rx_pause_control/pause_quanta_reg[*]] -to [get_cells bd_efdb_xmac_0_core/tx/tx_cntl/pause_tx_quanta_reg[*]]
set_property src_info {type:SCOPED_XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/fc_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.fc_en_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.tx_en_int_reg]
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.enable_dic_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.ifg_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.inband_fcs_en_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.jumbo_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/mtu_tx_reg[*]}] -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.user_max_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/mtu_tx_reg[*]}] -to [get_cells {bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.user_max_size_cap_reg[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.custom_preamble_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.vlan_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.stacked_vlan_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.rx_en_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.inband_crc_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.cust_preamble_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.rx_lt_disable_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.pause_length_disable_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx0_reg[*]}]     -to [get_cells {bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.unicast_addr_low_out_reg[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/pause_addr_hi_reg[*]}] -to [get_cells {bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.unicast_addr_hi_out_reg[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.jumbo_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.vlan_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/fc_reg[*]}]       -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.fc_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.stacked_vlan_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.enhanced_vlan_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/mtu_rx_reg[*]}]  -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.user_max_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/mtu_rx_reg[*]}]  -to [get_cells {bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.user_max_size_cap_reg[*]}]
current_instance
current_instance ethernet_core_0_B/inst/xmac/inst
set_property src_info {type:SCOPED_XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells bd_efdb_xmac_0_core/rx/rx_pause_control/pause_quanta_reg[*]] -to [get_cells bd_efdb_xmac_0_core/tx/tx_cntl/pause_tx_quanta_reg[*]]
set_property src_info {type:SCOPED_XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/fc_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.fc_en_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.tx_en_int_reg]
set_property src_info {type:SCOPED_XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.enable_dic_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.ifg_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.inband_fcs_en_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.jumbo_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/mtu_tx_reg[*]}] -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.user_max_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/mtu_tx_reg[*]}] -to [get_cells {bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.user_max_size_cap_reg[*]}]
set_property src_info {type:SCOPED_XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.custom_preamble_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.vlan_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/tx_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/tx/tx_config_sync/MAN_USED.stacked_vlan_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.rx_en_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.inband_crc_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.cust_preamble_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.rx_lt_disable_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.pause_length_disable_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx0_reg[*]}]     -to [get_cells {bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.unicast_addr_low_out_reg[*]}]
set_property src_info {type:SCOPED_XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/pause_addr_hi_reg[*]}] -to [get_cells {bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.unicast_addr_hi_out_reg[*]}]
set_property src_info {type:SCOPED_XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.jumbo_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.vlan_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/fc_reg[*]}]       -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.fc_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.stacked_vlan_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/rx1_reg[*]}]     -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.enhanced_vlan_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/mtu_rx_reg[*]}]  -to [get_cells bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.user_max_enable_cap_reg]
set_property src_info {type:SCOPED_XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells {bd_efdb_xmac_0_core/control_block/USE_MAN.register_block/mtu_rx_reg[*]}]  -to [get_cells {bd_efdb_xmac_0_core/rx/rx_config_sync/MAN_USED.user_max_size_cap_reg[*]}]
current_instance
current_instance ethernet_core_0_A/inst/xpcs/inst
set_property src_info {type:SCOPED_XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync*d4_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync*d5_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -to [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync*outreg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync*outreg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_resyncs_i*d4_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_resyncs_i*d5_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -to [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_resyncs_i*outreg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_resyncs_i*outreg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR || PRIMITIVE_SUBGROUP =~ srl)}]
set_property src_info {type:SCOPED_XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path 2 -from [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -of [filter [all_fanout -flat -endpoints_only -from [get_pins -filter {NAME=~*/Q} -of_objects [get_cells -hierarchical -filter {NAME =~ *rxratecounter_i*rxusrclk2_en156*}]]] {NAME =~ *WE}]]
set_property src_info {type:SCOPED_XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -of [filter [all_fanout -flat -endpoints_only -from [get_pins -filter {NAME=~*/Q} -of_objects [get_cells -hierarchical -filter {NAME =~ *rxratecounter_i*rxusrclk2_en156*}]]] {NAME =~ *WE}]]
set_property src_info {type:SCOPED_XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*rd_truegray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*rag_writesync0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*wr_gray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*wr_gray_rdclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 3.100
set_property src_info {type:SCOPED_XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*rd_lastgray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*rd_lastgray_wrclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *txrate*rd_truegray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *txrate*rag_writesync0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 3.100
set_property src_info {type:SCOPED_XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *txrate*wr_gray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *txrate*wr_gray_rdclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *txrate*rd_lastgray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *txrate*rd_lastgray_wrclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 3.100
set_property src_info {type:SCOPED_XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -of [all_fanin -flat [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *resyncs*d1_reg}] -filter {NAME =~ *D}]] -filter {IS_SEQUENTIAL=="1" && NAME !~ "*resyncs*d1_reg"}] -to [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *resyncs*d1_reg}] -filter {NAME =~ *D}] 3.100 -datapath_only
set_property src_info {type:SCOPED_XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_clocks -of_objects [get_ports refclk_p]] -to [get_pins -of_objects [get_cells -hier -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync/*synchc_inst*d1_reg}] -filter {NAME =~ *D}] 6.400
set_property src_info {type:SCOPED_XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hierarchical -filter {NAME =~ *drp_ipif_i*synch_*d_reg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *drp_ipif_i*synch_*q_reg*}] -filter {NAME =~ *D || NAME =~ *R || NAME =~ *S}] 3.100
current_instance
current_instance ethernet_core_0_B/inst/xpcs/inst
set_property src_info {type:SCOPED_XDC file:4 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync*d4_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync*d5_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -to [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync*outreg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:4 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync*outreg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_resyncs_i*d4_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_resyncs_i*d5_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:4 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -to [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_resyncs_i*outreg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:4 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *coreclk_rxusrclk2_resyncs_i*outreg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}]
set_property src_info {type:SCOPED_XDC file:4 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR || PRIMITIVE_SUBGROUP =~ srl)}]
set_property src_info {type:SCOPED_XDC file:4 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path 2 -from [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -of [filter [all_fanout -flat -endpoints_only -from [get_pins -filter {NAME=~*/Q} -of_objects [get_cells -hierarchical -filter {NAME =~ *rxratecounter_i*rxusrclk2_en156*}]]] {NAME =~ *WE}]]
set_property src_info {type:SCOPED_XDC file:4 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -from [get_cells * -hierarchical -filter {NAME =~ *mcp1_* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -of [filter [all_fanout -flat -endpoints_only -from [get_pins -filter {NAME=~*/Q} -of_objects [get_cells -hierarchical -filter {NAME =~ *rxratecounter_i*rxusrclk2_en156*}]]] {NAME =~ *WE}]]
set_property src_info {type:SCOPED_XDC file:4 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*rd_truegray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*rag_writesync0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:4 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*wr_gray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*wr_gray_rdclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 3.100
set_property src_info {type:SCOPED_XDC file:4 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*rd_lastgray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*rd_lastgray_wrclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *txrate*rd_truegray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *txrate*rag_writesync0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 3.100
set_property src_info {type:SCOPED_XDC file:4 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *txrate*wr_gray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *txrate*wr_gray_rdclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:4 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *txrate*rd_lastgray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *txrate*rd_lastgray_wrclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 3.100
set_property src_info {type:SCOPED_XDC file:4 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -of [all_fanin -flat [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *resyncs*d1_reg}] -filter {NAME =~ *D}]] -filter {IS_SEQUENTIAL=="1" && NAME !~ "*resyncs*d1_reg"}] -to [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *resyncs*d1_reg}] -filter {NAME =~ *D}] 3.100 -datapath_only
set_property src_info {type:SCOPED_XDC file:4 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_clocks -of_objects [get_ports refclk_p]] -to [get_pins -of_objects [get_cells -hier -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync/*synchc_inst*d1_reg}] -filter {NAME =~ *D}] 6.400
set_property src_info {type:SCOPED_XDC file:4 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hierarchical -filter {NAME =~ *drp_ipif_i*synch_*d_reg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *drp_ipif_i*synch_*q_reg*}] -filter {NAME =~ *D || NAME =~ *R || NAME =~ *S}] 3.100
current_instance
set_property src_info {type:XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U24 [get_ports clk]
set_property src_info {type:XDC file:5 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports key1]
set_property src_info {type:XDC file:5 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H25 [get_ports {led_A[2]}]
set_property src_info {type:XDC file:5 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H26 [get_ports {led_A[1]}]
set_property src_info {type:XDC file:5 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G27 [get_ports {led_A[0]}]
set_property src_info {type:XDC file:5 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC19 [get_ports {led_B[2]}]
set_property src_info {type:XDC file:5 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC20 [get_ports {led_B[1]}]
set_property src_info {type:XDC file:5 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE20 [get_ports {led_B[0]}]
set_property src_info {type:XDC file:5 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports gtrefclk0_p_A]
set_property src_info {type:XDC file:5 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports gtrefclk0_n_A]
set_property src_info {type:XDC file:5 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports gtrefclk0_p_B]
set_property src_info {type:XDC file:5 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports gtrefclk0_n_B]
set_property src_info {type:XDC file:5 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports sfp_tx_disable_A]
set_property src_info {type:XDC file:5 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports sfp_rate_A]
set_property src_info {type:XDC file:5 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10 [get_ports sfp_rx_p_A]
set_property src_info {type:XDC file:5 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F9 [get_ports sfp_rx_n_A]
set_property src_info {type:XDC file:5 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C8 [get_ports sfp_tx_p_A]
set_property src_info {type:XDC file:5 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C7 [get_ports sfp_tx_n_A]
set_property src_info {type:XDC file:5 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ifcA [get_pins clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]
set_property src_info {type:XDC file:5 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -name async_clock_A -asynchronous -group [get_clocks ifcA] -group [get_clocks gtrefclk0_p_A]
set_property src_info {type:XDC file:5 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports sfp_tx_disable_B]
set_property src_info {type:XDC file:5 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports sfp_rate_B]
set_property src_info {type:XDC file:5 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10 [get_ports sfp_rx_p_B]
set_property src_info {type:XDC file:5 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D9 [get_ports sfp_rx_n_B]
set_property src_info {type:XDC file:5 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A8 [get_ports sfp_tx_p_B]
set_property src_info {type:XDC file:5 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A7 [get_ports sfp_tx_n_B]
set_property src_info {type:XDC file:5 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ifcB [get_pins clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]
set_property src_info {type:XDC file:5 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -name async_clock_B -asynchronous -group [get_clocks ifcB] -group [get_clocks gtrefclk0_p_B]
set_property src_info {type:XDC file:5 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -include_generated_clocks ifcA] -to [get_clocks ifcB]
set_property src_info {type:XDC file:5 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -include_generated_clocks ifcB] -to [get_clocks ifcA]
current_instance ethernet_core_0_A/inst/xmac/inst
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_ports s_axi_aclk]] -to [get_cells {bd_efdb_xmac_0_core/tx/tx_cntl/pause_tdata_reg[*]}]
current_instance
current_instance ethernet_core_0_B/inst/xmac/inst
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_ports s_axi_aclk]] -to [get_cells {bd_efdb_xmac_0_core/tx/tx_cntl/pause_tdata_reg[*]}]
