# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.runs/synth_2_420/.Xil/Vivado-10056-DESKTOP-DMECAJG/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7k420tiffg901-2L
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axis_data_fifo_0/hdl
    d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_1
    d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_0
  } {
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axis_data_fifo_0/hdl
    d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_1
    d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_0
  } {
      D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/SizedFIFO.v
      D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/example/axi_10g_ethernet_0_axi_lite_sm.v
      D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/example/axi_10g_ethernet_0_sync_block.v
      D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/example/axi_10g_ethernet_0_sync_reset.v
      D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/mkEthernet.v
      D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/mkFilter.v
      D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/mkIP.v
      D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/mkNetwork.v
      D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/mkTCP.v
      D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/udp_ip_10g_sfp/udp_transmit_test.v
    }
      rt::read_verilog -include {
    d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axis_data_fifo_0/hdl
    d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_1
    d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_0
  } {
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/hdl/ten_gig_eth_mac_v15_1_rfs.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/ten_gig_eth_mac_v15_1_1/hdl/bd_efdb_xmac_0_core.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0_sync_resetn.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0_block.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/hdl/ten_gig_eth_pcs_pma_v6_0_rfs.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_gtwizard_10gbaser_gt.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_gtwizard_10gbaser_multi_gt.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_ff_synchronizer_rst.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_ff_synchronizer.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_local_clock_and_reset.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_sim_speedup_controller.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_cable_pull_logic.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_block.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_support.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_shared_clock_and_reset.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_gt_common.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_ff_synchronizer_rst2.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_2/xlconstant.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_2/sim/bd_efdb_prtad_driver_0.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_3/sim/bd_efdb_dcm_locked_driver_0.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_4/sim/bd_efdb_pma_pmd_type_driver_0.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/hdl/bd_efdb.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/synth/axi_10g_ethernet_0.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axis_data_fifo_0/hdl/axis_infrastructure_v1_1_vl_rfs.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axis_data_fifo_0/hdl/axis_data_fifo_v2_0_vl_rfs.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axis_data_fifo_0/synth/axis_data_fifo_0.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_clk_wiz.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v
      d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top sfp_10G
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.runs/synth_2_420/.Xil/Vivado-10056-DESKTOP-DMECAJG/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
