# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.runs/synth_2_420/sfp_10G.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_2_420" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k420tiffg901-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.cache/wt [current_project]
set_property parent.project_path D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/SizedFIFO.v
  D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/example/axi_10g_ethernet_0_axi_lite_sm.v
  D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/example/axi_10g_ethernet_0_sync_block.v
  D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/example/axi_10g_ethernet_0_sync_reset.v
  D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/mkEthernet.v
  D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/mkFilter.v
  D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/mkIP.v
  D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/mkNetwork.v
  D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/firewall-filter/mkTCP.v
  D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/imports/udp_ip_10g_sfp/udp_transmit_test.v
}
read_ip -quiet D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/axi_10g_ethernet_0.xci
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_xmac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_xpcs_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/bd_efdb_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axi_10g_ethernet_0/synth/axi_10g_ethernet_0_ooc.xdc]

read_ip -quiet D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci

read_ip -quiet D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_late.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/constrs_1/new/udp_ip_10g.xdc
set_property used_in_implementation false [get_files D:/GitHub/IDS/Código_VIVADO/filter_10g_sfp.srcs/constrs_1/new/udp_ip_10g.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top sfp_10G -part xc7k420tiffg901-2L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sfp_10G.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_2_420_synth_report_utilization_0" "report_utilization -file sfp_10G_utilization_synth.rpt -pb sfp_10G_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_2_420" END { }
